### ISSUE TITLE
Sorting emote sets

### ISSUE THREAD

**Issue by CallumJThompson** [SevenTV/Website#1006]
### Tell us about your Wish

Currently, emote sets don't seem to have any form of sorting. This makes changing emotes in emote sets a little bothersome. Say there's an emote that is now unavailable, I have to browse the whole list to find all the 'No Longer Available' emotes. An addition of sorting emotes with certain tags applied to them would make this process a lot quicker.

### Is your feature related to a bug

No

### Additional Info

Sorting filters that **should** be available:
- Alphabetical (A-Z)
- Popularity (Asc-Desc) (Similar to Emote Directory's popularity filter)
- Date Added (Oldest-Newest)
- Tags (Renamed In Set, Global Emote, Unlisted, No Longer Available)

Filters that may/would be harder to implement (or just not as high priority), but would be nice additions:
- Visually similar emotes (For emotes that may be the same but have different names, bypassing the conflict)
- Sort by Author (A-Z)

There may be more I've missed, but these are the filters I've thought of.

### Participation

- [ ] I am willing to submit a pull request to implement this

**Comment by TroyKomodo** [comment]
We dont plan to do any more feature requests against this repo. We are in the process of redesigning the website.
For more info please see https://github.com/SevenTV/SevenTV/
