### ISSUE TITLE
Emote export to Telegram / Whatsapp Stickers

### ISSUE THREAD

**Issue by Niko32** [SevenTV/Website#1011]
### Tell us about your Wish

It would be really cool to be able to make sticker packs for telegram and whatsapp. I imagine making a sticker pack from the emotes used on a certain channel and being able to download that.

### Participation

- [ ] I am willing to submit a pull request to implement this

**Comment by Niko32** [comment]
I would have liked to contribute but I can't pay for fontawesome pro

**Comment by TroyKomodo** [comment]
We dont plan to do any more feature requests against this repo. We are in the process of redesigning the website.
For more info please see https://github.com/SevenTV/SevenTV/
