### ISSUE TITLE
Main Page - Large Community & Footer text translation

### ISSUE THREAD

**Issue by KiritoStorm** [SevenTV/Website#613]
All parts on the home page are correctly translated, except the one with large community. (under Why 7tv?)
It's allways in English.

![image](https://user-images.githubusercontent.com/46503102/185785392-22cd69d1-9a3e-4a92-ab9a-91a71f02f7c2.png)

I also wanted to mention that the legal footer is also not translated at the moment.

![image](https://user-images.githubusercontent.com/46503102/185785514-7a6cc34c-e356-4096-a329-8fabf6875cbc.png)

**Comment by AnatoleAM** [comment]
To submit translations please refer to the [Crowdin Project](https://translate.7tv.app), which website translations are downstream from.

**Comment by KiritoStorm** [comment]
Oh sry, I guess this is the [correct link](https://crowdin.com/project/7tv).
