### ISSUE TITLE
(Browser) Right-click in emote set list changes your default set

### ISSUE THREAD

**Issue by TranRed** [SevenTV/Website#668]
**Description:**
When right-clicking an entry in the list of emote sets you are editor of, the context menu open and the website assigns this set as your default.

**Expected behaviour:**

1. Only the browser context menu should open. 
2. Default assignment should only be changed by the menu entry on the right. ("Assign As Default")

**Tested browsers:**
Firefox and Chrome

**Screenshot (recording):**
![chrome_pNVfcgd7OQ](https://user-images.githubusercontent.com/16636423/189478226-a4b45743-3359-4479-b73f-f97436552fc1.gif)

**Comment by AnatoleAM** [comment]
Intended behavior
