### ISSUE TITLE
Editors can't add emotes until streamer has added one

### ISSUE THREAD

**Issue by eltharynd** [SevenTV/Website#682]
Reproduce:
Register as a new user, add someone as editor, editor can't add emotes to that channel.

Pretty sure it's because the emote set isn't created until you add your first emote, so you won't show up for the editors.
I suggest creating the first emote set when you create the user to fix (so maybe this issue should go to API really)

**Comment by AnatoleAM** [comment]
Intended behavior. The "Manage Emote Sets" permission will become effective with #689 allowing editors to create emote sets on behalf of another user.

**Comment by eltharynd** [comment]
@AnatoleAM pls reopen as not intended behaviour.

I get those permissions, but what i mean is if the streamer is new (so no emote set yet) editors can't add emotes at ALL, not even to the default emote set that streamer can already see.

**Comment by AnatoleAM** [comment]
@eltharynd You can create an Emote Set for a streamer if you have the "Manage Emote Sets" editor permission.
