### ISSUE TITLE
Processing error only shows on direct emote uploads

### ISSUE THREAD

**Issue by Infinitay** [SevenTV/Website#684]
If you face a processing error when uploading new version of an existing emote it won't be displayed to you as it would if you try to upload a new emote.

For reference, this it the error page I am referring to:
![image](https://user-images.githubusercontent.com/6964154/190941558-a72b1601-e525-45eb-86cb-226fdbb98c64.png)

**Comment by TroyKomodo** [comment]
We dont plan to implement this bug before the rewrite.
For more info please see https://github.com/SevenTV/SevenTV/
