### ISSUE TITLE
[bug] DevTools failed to load source map: Could not parse content for https://7tv.app/window-provider.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by iamflorencejay** [SevenTV/Website#713]
I want to add emote, but it appears on my list.
![brave_L7HQTxrKRD](https://user-images.githubusercontent.com/24932514/194225997-5700e293-b0d1-4007-b0a5-a6d57913f23d.png)

**Comment by TroyKomodo** [comment]
We dont plan to implement this bug before the rewrite.
For more info please see https://github.com/SevenTV/SevenTV/
