### ISSUE TITLE
[Enhancement] Bulk add/remove Emote Set from another one

### ISSUE THREAD

**Issue by Mr-Reca** [SevenTV/Website#770]
Dear all,

One use case for Emote Set is the management of "season emotes" like Spooky or Christmas, or temporary emotes (e.g. Minecraft event, Emote Set with Minecraft emotes, Pokemon event, etc.). In my case, I created two Emote Set: one contains the season emotes, and the other one that same season emotes but they are "standard".

Using this, I am able to "quick update" the main Emote set (removing all from the standar emote set, then applying the season emote set). This also happens because there are some Emotes that are not seasonal or they are from the channel itself. Nowadays, remove 80 emote and apply 80 new ones (or adding and click the "replace conflict".

I think it would be interesting to bulk add / bulk remove an emote set using another one, also taking into account the renamed name in the emote set (apply the renamed emote to the Main Emote Set).

Thanks in advance

**Comment by TroyKomodo** [comment]
We dont plan to implement this feature before the rewrite.
For more info please see https://github.com/SevenTV/SevenTV/
