### ISSUE TITLE
Searching for an emote that does not exist in the Owned Emotes section of a user causes the search field to disappear

### ISSUE THREAD

**Issue by ichigo-gyunyu** [SevenTV/Website#791]
It's probably easier to explain with screenshots

![2022-11-30_21:20:26](https://user-images.githubusercontent.com/15829692/204844909-35d1fd62-7435-47de-ae09-2a8750b7d4a8.png)
The page on load

![2022-11-30_21:20:36](https://user-images.githubusercontent.com/15829692/204844934-3f7cdf0b-293b-49f1-b4d5-f1a25ce4bd7b.png)
Filter functionality works fine when searching

![2022-11-30_21:20:43](https://user-images.githubusercontent.com/15829692/204844941-9efd2e59-4e42-4e46-9c1c-5c3943750ee5.png)
If no results are found, the entire Owned Emotes section disappears requiring a page reload.

Browser: Firefox 107.0

**Comment by TroyKomodo** [comment]
We dont plan to implement this bug before the rewrite.
For more info please see https://github.com/SevenTV/SevenTV/
