### ISSUE TITLE
Making versions of an emote, then deleting the original before approval, causes `owned_emotes` to be stuck in deleted state

### ISSUE THREAD

**Issue by brian6932** [SevenTV/Website#804]
_The `#bugs-and-stuff` channel on Discord has has been archived, so I'm converting some issues to GitHub ones_
1. Upload an emote
2. Upload a 2nd version
3. Delete the 1st version
4. Since emotes link to their original version in `owned_emotes`, and there's no way to set a default version _yet_

<details>
	<summary>owned_emotes</summary>

```json
{
	"data":
	{
		"user":
		{
			"owned_emotes":
			[
				{
					"id": "63615a32545fbd7ba91acc69",
					"name": "EvilAnya"
				},
				{
					"id": "636307172931d7f7a6833948",
					"name": "PepeHands"
				}
			]
		}
	}
}
```

</details>

This results in the site showing them as deleted, even though they are listed
![](https://i.alienpls.org/xIQ.png)
- Adding the newest version emote hash works fine
- The newest version does show in public listings
- Activity done for approval by mods doesn't show on the new id

<details>
	<summary>emote_set.emotes</summary>

```json
{
	"emotes": [
		{
			"id": "63615bb776ed2d74d9ed2bc7",
			"name": "EvilAnya"
		},
		{
			"id": "636308c41f7fe924a876f1f2",
			"name": "PepeHands"
		}
	]
}
```

</details>

Ideally this should just link to the new version of the emote, filter out the null/undefined/unreachable value

**Comment by AnatoleAM** [comment]
> The #bugs-and-stuff channel on Discord has has been archived

It's a forum channel now

**Comment by brian6932** [comment]
Yea I know ripcord doesn't support that tho 💀

**Comment by brian6932** [comment]
Versioning no longer exists
