### ISSUE TITLE
.mov files actually supports transparency (But the 7tv page says the opposite)

### ISSUE THREAD

**Issue by Fijxu** [SevenTV/Website#850]
So, some days ago i deleted the background of some video using Kdenlive and i exported it as a .mov
There is not to many info to add here anyways, here is the actual magic number of the .mov that i uploaded to 7tv and the emote link

Link: https://7tv.app/emotes/63950b3686f6cfe33ed3cebc
.mov: https://i.ayaya.beauty/YfJMvnvP.mov

Magic Numbers match
![](https://i.ayaya.beauty/uHNCstBE.png)

**Comment by TroyKomodo** [comment]
Interesting, i did not know.
---
We dont plan to fix this bug before the rewrite.
For more info please see https://github.com/SevenTV/SevenTV/
