### ISSUE TITLE
 `set-output` command is deprecated 

### ISSUE THREAD

**Issue by Geczy** [SevenTV/Website#896]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/SevenTV/Website/blob/dev/.github/workflows/crowdin-download.yaml

**Comment by TroyKomodo** [comment]
We dont plan to fix this bug before the rewrite.
For more info please see https://github.com/SevenTV/SevenTV/
