### ISSUE TITLE
[Enhancement] Allow adding emote set from another channel to your channel

### ISSUE THREAD

**Issue by WUOTE** [SevenTV/Website#931]
That will make sharing emote collections quick and easy without manually adding emotes one by one, especially for [sets with many emotes (WIP)](https://7tv.app/emote-sets/640068c6df157664ba970988)

**Comment by TroyKomodo** [comment]
We dont plan to do any more feature requests against this repo. We are in the process of redesigning the website.
For more info please see https://github.com/SevenTV/SevenTV/
