### ISSUE TITLE
[Enhancement] Show Namepaints directly for your own username

### ISSUE THREAD

**Issue by dasgehtyannick** [SevenTV/Website#932]
I would love to instantly see every available name paints for my specific username. Some name paints look better on longer usernames and I would love to try out a name paint before saving it.

Possible approach could be to add a button below the name paints to "Preview Paints with Name" and every Name Paint Name would switch to the username.

(Example bottom row "brain")
![image](https://user-images.githubusercontent.com/60045903/222690503-1accc620-e1f9-45ab-a493-47269b8509fa.png)

**Comment by TroyKomodo** [comment]
We dont plan to do any more feature requests against this repo. We are in the process of redesigning the website.
For more info please see https://github.com/SevenTV/SevenTV/
