### ISSUE TITLE
old.7tv.app Login Broken

### ISSUE THREAD

**Issue by RealityRipple** [SevenTV/Website#936]
Attempting to log in to the old website results in the following error:
```{"status_code":404,"status":"Not Found","error":"Unknown Route","error_code":70498,"details":{"message":"The API endpoint requested does not exist"}}```
Because of this, linking an account to YouTube can't be achieved.

**Comment by BensonCoolfi** [comment]
i also got this error while trying to link my YouTube account

**Comment by velocinatortv** [comment]
hopefully they fix the routing soon, I accidentally unIinked, and cannot relink. I reported this on the discord, so hopefully it gets patched soon, I know they're probably focused on launching Kick right now but hopefully youtube doesn't get left behind in the dust again.

**Comment by AnatoleAM** [comment]
The old website is no longer supported. It is currently not possible to sign-in via youtube as we are unable to obtain access to Google's OAuth system, an alternative method will be added later.
