### ISSUE TITLE
Can't remove deleted Owned Emote from my profile

### ISSUE THREAD

**Issue by PriscillAAH** [SevenTV/Website#942]
I made an emote and deleted it, but it still shows on my profile. There's no longer a delete button because the emote has been deleted. 

Here's what it looks like:
![7sigViv](https://user-images.githubusercontent.com/32128443/224541929-3610320e-e1dc-475f-b3e5-8d7e402307c0.png)
![rXtMWxr](https://user-images.githubusercontent.com/32128443/224541960-ec9919d5-832e-42c9-b6f7-9405f3a2e32a.png)

**Comment by paulshadowsx** [comment]
This happened to me once, on the navigation menu select Emotes, then click on search and type your emote's name, select your emote and from there you can delete it.

**Comment by PriscillAAH** [comment]
thank you for the help this worked for me.
