### ISSUE TITLE
Activity section should include the channel name in logs

### ISSUE THREAD

**Issue by revelsix** [SevenTV/Website#963]
As of right now, it's currently formatted as `Added the emote [name] to`, which just looks incomplete.
It should include the channel name at the end in order to look less strange.
![image](https://user-images.githubusercontent.com/45189851/229646298-c3ed17d3-c180-4d73-aad5-9abf90d6641e.png)

**Comment by TroyKomodo** [comment]
We dont plan to do any more feature requests against this repo. We are in the process of redesigning the website.
For more info please see https://github.com/SevenTV/SevenTV/
