### ISSUE TITLE
Unable to set a profile picture

### ISSUE THREAD

**Issue by HeelMePlz** [SevenTV/Website#989]
Hi, I'm unable to set a profile picture on the 7TV website.

My profile always shows with the following:

![image](https://github.com/SevenTV/Website/assets/78705543/33da08fb-4df9-4947-8520-fc0fc777e374)

![image](https://github.com/SevenTV/Website/assets/78705543/d8997bf4-fc4f-471d-99a9-0e775cc8f7fd)

I tried signing out, removing the connection on my Twitch account to SevenTV and then signing back in. I also tried using various images to check it's not a problem with the image.

**Comment by AnatoleAM** [comment]
You have to be a subscriber to set a profile picture via 7TV.
